language: php

php:
  - "5.5"
  - "5.6"
  - "7.0"
  - "nightly"

sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction

script:
  - ant -keep-going
  - test-compile.sh

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647

cache:
  directories:
    - vendor
